In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

db = pd.read_csv('C://Users//eduar//Desktop//DEV//Football//PremierLeague//database.csv',index_col=None)

In [3]:
# Agrupar os dados por jogador e calcular a soma dos chutes ao gol e a contagem de aparições
db_agrupado = db.groupby(['Jogador','Equipe']).agg(
    Total_Gols=('Gols','sum'),
    Total_Chutes=('TC', 'sum'),   # Soma dos chutes ao gol
    Aparicoes=('Jogador', 'count'), # Contagem de aparições
    Total_Chutes_Gol=('CaG', 'sum'), # Contagem de aparições
).sort_values(by='Total_Chutes', ascending=False)  # Ordenar antes do reset_index

# Adicionar uma coluna de ranking
db_agrupado['Ranking'] = db_agrupado['Total_Chutes'].rank(method='min', ascending=False).astype(int)

# Adicionar uma coluna de média (Total_Chutes / Aparicoes)
db_agrupado['Média_Chutes'] = round(db_agrupado['Total_Chutes'] / db_agrupado['Aparicoes'],2)

db_agrupado['Média_Chutes_Gol'] = round(db_agrupado['Total_Chutes_Gol'] / db_agrupado['Aparicoes'],2)

# Resetar o índice
db_agrupado.reset_index(inplace=True)

# Reorganizar as colunas para que o Ranking seja a primeira
db_agrupado = db_agrupado[['Ranking', 'Jogador','Equipe' ,'Aparicoes','Total_Gols','Total_Chutes','Média_Chutes','Total_Chutes_Gol','Média_Chutes_Gol']]

In [10]:
db_agrupado = db_agrupado.sort_values(by=['Total_Chutes_Gol'],ascending=False)

jogos_do_dia = db_agrupado['Equipe'].isin(['Chelsea','Bournemouth'])
db_agrupado[jogos_do_dia].head(10)

,Ranking,Jogador,Equipe,Aparicoes,Total_Gols,Total_Chutes,Média_Chutes,Total_Chutes_Gol,Média_Chutes_Gol
8,9,Noni Madueke,Chelsea,2,3,9,4.50,6,3.00
35,28,Nicolas Jackson,Chelsea,3,2,6,2.00,5,1.67
4,4,Marcus Tavernier,Bournemouth,3,1,12,4.00,5,1.67
0,1,Antoine Semenyo,Bournemouth,3,2,17,5.67,4,1.33
44,37,Luis Sinisterra,Bournemouth,3,1,5,1.67,3,1.00
9,9,Cole Palmer,Chelsea,3,1,9,3.00,3,1.00
52,53,Evanilson,Bournemouth,2,0,4,2.00,2,1.00
83,76,João Félix,Chelsea,2,1,3,1.50,2,1.00
127,115,Levi Colwill,Chelsea,3,0,2,0.67,1,0.33
173,162,Lewis Cook,Bournemouth,3,1,1,0.33,1,0.33

In [13]:
db[db['Jogador'].isin(['Nicolas Jackson','Evanilson'])]

,Equipe,Jogador,#,Nação,Pos.,Idade,Min.,Gols,Assis.,PB,PT,TC,CaG,CrtsA,CrtV,Contatos,Div,Crts,Bloqueios,xG,npxG,xAG,SCA,GCA,Cmp,Att,Cmp%,PrgP,Conduções,PrgC,Tent,Suc,Data
250,Chelsea,Nicolas Jackson,15.0,SEN,FW,23-059,66,0,0,0,0,1,1,0,0,21,0,0,0,0.5,0.5,0.2,3,0,11,16,"68,8",2,10,0,0,0,2024-08-18
526,Bournemouth,Evanilson,9.0,BRA,FW,24-324,71,0,0,0,0,3,2,0,0,23,1,0,2,0.8,0.8,0.0,1,0,6,11,"54,5",1,10,1,2,1,2024-08-25
574,Chelsea,Nicolas Jackson,15.0,SEN,FW,23-066,67,1,1,0,0,1,1,0,0,33,0,0,1,0.2,0.2,0.1,3,2,18,21,"85,7",2,22,0,1,0,2024-08-25
664,Bournemouth,Evanilson,9.0,BRA,FW,24-330,64,0,0,0,0,1,0,0,0,17,0,0,0,0.2,0.2,0.0,2,0,9,11,"81,8",1,8,0,1,0,2024-08-31
867,Chelsea,Nicolas Jackson,15.0,SEN,FW,23-073,90,1,0,0,0,4,3,1,0,17,0,0,0,1.3,1.3,0.0,1,0,3,5,"60,0",0,9,3,3,1,2024-09-01

In [12]:
db_agrupado[jogos_do_dia].sort_values(by=['Total_Chutes'],ascending=False)

,Ranking,Jogador,Equipe,Aparicoes,Total_Gols,Total_Chutes,Média_Chutes,Total_Chutes_Gol,Média_Chutes_Gol
0,1,Antoine Semenyo,Bournemouth,3,2,17,5.67,4,1.33
4,4,Marcus Tavernier,Bournemouth,3,1,12,4.00,5,1.67
8,9,Noni Madueke,Chelsea,2,3,9,4.50,6,3.00
9,9,Cole Palmer,Chelsea,3,1,9,3.00,3,1.00
35,28,Nicolas Jackson,Chelsea,3,2,6,2.00,5,1.67
44,37,Luis Sinisterra,Bournemouth,3,1,5,1.67,3,1.00
52,53,Evanilson,Bournemouth,2,0,4,2.00,2,1.00
83,76,João Félix,Chelsea,2,1,3,1.50,2,1.00
92,76,Enzo Fernández,Chelsea,3,0,3,1.00,1,0.33
127,115,Levi Colwill,Chelsea,3,0,2,0.67,1,0.33
137,115,Justin Kluivert,Bournemouth,3,0,2,0.67,0,0.00
115,115,Dango Ouattara,Bournemouth,3,0,2,0.67,0,0.00
226,162,Christopher Nkunku,Chelsea,3,0,1,0.33,0,0.00
218,162,Illia Zabarnyi,Bournemouth,3,0,1,0.33,0,0.00
172,162,Alex Scott,Bournemouth,3,0,1,0.33,0,0.00
168,162,Moisés Caicedo,Chelsea,3,0,1,0.33,0,0.00
167,162,Milos Kerkez,Bournemouth,3,0,1,0.33,0,0.00
176,162,Pedro Neto,Chelsea,3,0,1,0.33,0,0.00
177,162,Malo Gusto,Chelsea,3,0,1,0.33,0,0.00
180,162,Wesley Fofana,Chelsea,3,0,1,0.33,0,0.00
173,162,Lewis Cook,Bournemouth,3,1,1,0.33,1,0.33
347,232,Kiernan Dewsbury-Hall,Chelsea,2,0,0,0.00,0,0.00
240,232,Robert Sánchez,Chelsea,3,0,0,0.00,0,0.00
311,232,Marc Cucurella,Chelsea,3,0,0,0.00,0,0.00
312,232,Marc Guiu,Chelsea,1,0,0,0.00,0,0.00
314,232,Marcos Senesi,Bournemouth,2,0,0,0.00,0,0.00
266,232,Daniel Jebbison,Bournemouth,2,0,0,0.00,0,0.00
263,232,Mykhailo Mudryk,Chelsea,2,0,0,0.00,0,0.00
260,232,Ryan Christie,Bournemouth,3,0,0,0.00,0,0.00
249,232,Philip Billing,Bournemouth,1,0,0,0.00,0,0.00
251,232,Roméo Lavia,Chelsea,1,0,0,0.00,0,0.00
287,232,Adam Smith,Bournemouth,3,0,0,0.00,0,0.00
271,232,Dean Huijsen,Bournemouth,2,0,0,0.00,0,0.00
232,232,Renato Veiga,Chelsea,2,0,0,0.00,0,0.00
239,232,Neto,Bournemouth,2,0,0,0.00,0,0.00
345,232,Julian Araujo,Bournemouth,3,0,0,0.00,0,0.00